# This is a basic workflow to help you get started with Actions

name: cosign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4.1.1

    - uses: sigstore/cosign-installer@v3.3.0

    - name: Sign image with a key
      run: |
        echo cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY README.md
        cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY README.md
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
