# This is a basic workflow to help you get started with Actions

name: cosign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile site assets
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4.1.1

    - uses: sigstore/cosign-installer@v3.3.0

    - name: Sign image with a key
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        echo -e '\n======\nbash variable = ' "$COSIGN_PRIVATE_KEY" "\n======\n"
        echo -e '\n======\ncosign syntax = ' "env://COSIGN_PRIVATE_KEY" "\n======\n"
        echo -e '\n======\ngithub env = ' "${{ env.COSIGN_PRIVATE_KEY }}" "\n======\n"
        echo -e '\n======\ngithub secret  = ' "${{ secrets.COSIGN_PRIVATE_KEY }}" "\n======\n"
        cosign sign-blob --yes \
          --key env://COSIGN_PRIVATE_KEY "${{ env.FILE2SIGN }}" \
          --output-signature "${{ env.FILE2SIGN }}.sig"
        # cosign verify-blob \
        #   --key env://COSIGN_PUBLIC_KEY \
        #   --signature "${{ env.FILE2SIGN }}.sig" \
        #   "${{ env.FILE2SIGN }}"
        echo env://COSIGN_PUBLIC_KEY > cosign.pub
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        FILE2SIGN: "Vagrantfile"

    - name: Sign image with a key
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        Write-Output "`n======`npw variable = $env:COSIGN_PRIVATE_KEY `n======`n"
        Write-Output "`n======`ncosign syntax = env://COSIGN_PRIVATE_KEY `n======`n"
        Write-Output "`n======`ngithub env = ${{ env.COSIGN_PRIVATE_KEY }} `n======`n"
        Write-Output "`n======`ngithub secret  = ${{ secrets.COSIGN_PRIVATE_KEY }} `n======`n"
        
        cosign sign-blob --yes \
          --key "env://COSIGN_PRIVATE_KEY" "${{ env.FILE2SIGN }}" \
          --output-signature "${{ env.FILE2SIGN }}.sig"
        echo $env:COSIGN_PUBLIC_KEY > cosign.pub
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        FILE2SIGN: "Vagrantfile"

    - uses: actions/upload-artifact@v4.3.1
      with:
        name: cosign-pub
        path: |
          cosign.pub
          cosign
