# This is a basic workflow to help you get started with Actions

name: dev-env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os:
        - windows-latest
        # - ubuntu-latest	
        # - ubuntu-20.04
        # - macos-latest
        python-version:
        - '3.10.11'
          
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install python locally
        run: |
         choco install --no-progress innoextract
         curl -o python.exe https://www.python.org/ftp/python/${{ matrix.python-version }}/python-${{ matrix.python-version }}-amd64.exe
         innoextract python.exe
         ls
         ls app
         # ls python
         # python\python.exe --version
         # python\python.exe -m venv venv
         # venv\Scripts\activate.bat

