name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Generate Warning Annotations
      run: |
        url="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        text="This is a Warning, or isn't it? <a href='$url'>Press me</a>"
        echo "::warning file=app.js,line=1,col=5::$text"
    
    - name: Build the Docker image
      run: touch x.aaa

    - uses: actions/upload-artifact@v4
      with:
        path: x.aaa

    
