name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Generate Warning Annotations
      run: |
        url="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        text="This is a Warning, or isn't it? <a href='$url'>Press me</a>"
        # echo "::warning file=app.js,line=1,col=5::$text"
        # echo "::warning file=README.md,line=1,title=testing links::download-artifact $url"
        echo "::notice file=app.js,line=1,col=5,endColumn=7::You can visit [press me]($url) for more information."
        echo "::notice file=app.js,line=1,col=5,endColumn=7::You can visit $url for more information."
        echo "::notice file=app.js,line=1,col=5,endColumn=7,title=$url::To download artifact, visit the url."



    
    - name: Build the Docker image
      run: touch x.aaa

    - uses: actions/upload-artifact@v4
      with:
        path: x.aaa

    
