name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Generate Warning Annotations
      run: |
        url="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "::notice file=app.js,line=1,col=5,endColumn=7,title=Download artificat without login visiting the below url::$url."
    
    - name: Build the Docker image
      run: touch x.aaa

    - uses: actions/upload-artifact@v4
      with:
        path: x.aaa

    
