# This is a basic workflow to help you get started with Actions

name: ssh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Docker version
      run: docker --version
    - name: Docker build
      run: docker build -t sshserver .
    - name: sshpass
      run: sudo apt-get install sshpass
    - name: Docker run
      run: |
        docker run -dit -p 3000:22 --name sshserver sshserver:latest &
        sleep 10
        sshpass -p 'password' ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
        echo $?
        pkill docker

    # - name: Docker run
    #   uses: JarvusInnovations/background-action@v1
    #   with:
    #     run: |
    #       docker run -dit -p 3000:22 --name prova prova:latest
    #     wait-on: |
    #       http://localhost:3000
    #     # tail: true
    #     # log-output-resume: stderr
    #     wait-for: 1m
    #     # log-output: stderr,stdout
    #     # log-output-if: failure
    #     # working-directory: backend
    - name: test
      run: |
        echo ciao
                

    # - name: Upload image
    #   uses: ishworkh/container-image-artifact-upload@v1.0.0
    #   with:
    #     image: "sshserver:latest"

  # compile-win:
  #   name: Compile site assets
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout the repo
  #     uses: actions/checkout@v2
  #   - name: Docker version
  #     run: docker --version
  #   - name: Docker build
  #     run: docker build -t sshserver .
  #   - name: Upload image
  #     uses: ishworkh/container-image-artifact-upload@v1.0.0
  #     with:
  #       image: "sshserver:latest"