# This is a basic workflow to help you get started with Actions

name: ssh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Docker version
      run: docker --version
    - name: Docker build
      run: docker build -t sshserver .
    - name: Docker run
      uses: JarvusInnovations/background-action@v1
      with:
        run: |
          docker run -dit -p 3000:22 --name prova prova:latest
        # your step-level and job-level environment variables are available to your commands as-is
        # npm install will count towards the wait-for timeout
        # whenever possible, move unrelated scripts to a different step
        # to background multiple processes: add & to the end of the command

        wait-on: |
          http://localhost:3000

        # IMPORTANT: to use environment variables in wait-on, you must use this form: ${{ env.VAR }}
        # See wait-on section below for all resource types and prefixes

        tail: true # true = stderr,stdout
        # This will allow you to monitor the progress live

        log-output-resume: stderr
        # Eliminates previosuly output stderr log entries from post-run output

        wait-for: 1m

        log-output: stderr,stdout # same as true

        log-output-if: failure
        # failure = exit-early or timeout

        working-directory: backend
        # sets the working directory (cwd) for the shell running commands    
    - name: test
      run: |
        echo ciao
                

    # - name: Upload image
    #   uses: ishworkh/container-image-artifact-upload@v1.0.0
    #   with:
    #     image: "sshserver:latest"

  # compile-win:
  #   name: Compile site assets
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout the repo
  #     uses: actions/checkout@v2
  #   - name: Docker version
  #     run: docker --version
  #   - name: Docker build
  #     run: docker build -t sshserver .
  #   - name: Upload image
  #     uses: ishworkh/container-image-artifact-upload@v1.0.0
  #     with:
  #       image: "sshserver:latest"