# This is a basic workflow to help you get started with Actions

name: ssh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install paramiko==3.0

    - name: Docker build
      run: docker build -t sshserver . 

    - name: Docker run
      run: |
        nohup docker run -dit -p 3000:22 --name sshserver sshserver:latest > nohup.out 2> nohup.err < /dev/null &
        sleep 2

    - name: sshpass
      run: |
        sudo apt-get install sshpass
        sshpass -p 'password' ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
        echo $?
    
    - name: paramiko
      run: |
        python test_paramiko.py localhost sshuser 3000 password True
      
    - name: Docker kill
      run: |
        docker kill sshserver


        # python RCM/tests/test_paramiko.py localhost sshserver 3000 password True
        # ssh-keygen -t ecdsa -b 256 -f /tmp/sshkey -q -N ""
        # sshpass -p 'password' ssh-copy-id -i /tmp/sshkey -p 3000 sshuser@localhost
        # eval $(ssh-agent)
        # ssh-add /tmp/sshkey
        # ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
        # python RCM/tests/test_paramiko.py localhost sshserver 3000 None True
        


    # - name: Upload image
    #   uses: ishworkh/container-image-artifact-upload@v1.0.0
    #   with:
    #     image: "sshserver:latest"

  # compile-win:
  #   name: Compile site assets
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout the repo
  #     uses: actions/checkout@v2
  #   - name: Checkout the repo
  #     uses: actions/checkout@v2

    # - name: sshpass
    #   run: |
    #     choco install sshpass
    #     sshpass -p 'password' ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
    #     echo $?